FROM golang:1.20
WORKDIR /spootifer
COPY . ./
EXPOSE 8080
EXPOSE 8080
RUN go mod download
RUN go build -buildvcs=false -ldflags "-s -w -extldflags '-static'" -tags osusergo,netgo -o /spootifer .
ENTRYPOINT /spootifer/spootifer
ENV DATABASE_PATH=/db/spootifer.db
RUN ./setup-db.sh
