FROM golang:1.20 AS builder
WORKDIR /spootifer
COPY . ./
EXPOSE 8080
EXPOSE 8080
RUN go build -buildvcs=false -ldflags "-s -w -extldflags '-static'" -tags osusergo,netgo -o /spootifer .
ENTRYPOINT /spootifer/spootifer